name: Update Site Links

on:
  push:
    paths:
      - "_posts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate site-links.html
        shell: bash
        run: |
          set -euo pipefail
          out="site-links.html"
          cat > "$out" <<'HTML'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <link rel="stylesheet" href="assets/css/style.css">
            <title>All Posts</title>
          </head>
          <body>
            <h2>All Posts</h2>
            <div class="card-grid">
          HTML

          shopt -s nullglob
          for file in _posts/*.html; do
            fname=$(basename "$file")
            title=$(sed -n 's:.*<title>\(.*\)</title>.*:\1:p' "$file" | head -n1)
            [ -z "$title" ] && title="$fname"
            date=$(sed -n 's:.*<small>\(.*\)</small>.*:\1:p' "$file" | head -n1)
            summary=$(sed -n 's:.*<p>\(.*\)</p>.*:\1:p' "$file" | head -n1)
            summary=$(echo "$summary" | awk '{for(i=1;i<=30 && i<=NF;i++) printf $i" "; if(NF>30) printf "..."; print ""}')
            cat >> "$out" <<EOF
            <div class="card">
              <h3><a href="_posts/$fname">$title</a></h3>
              <p class="date">$date</p>
              <p class="summary">$summary</p>
            </div>
EOF
          done

          cat >> "$out" <<'HTML_END'
            </div>
          </body>
          </html>
          HTML_END

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add site-links.html
          git commit -m "Update site-links.html" || echo "No changes to commit"
          git push
